if( LIBSSH2_INCLUDE_DIR AND LIBSSH2_LIBRARY )
	set( LIBSSH2_FIND_QUIETLY true )
endif( LIBSSH2_INCLUDE_DIR AND LIBSSH2_LIBRARY )

find_path( LIBSSH2_INCLUDE_DIR libssh2.h )

find_library( LIBSSH2_LIBRARY NAMES ssh2 )

include( FindPackageHandleStandardArgs )
find_package_handle_standard_args( LibSSH2 DEFAULT_MSG LIBSSH2_INCLUDE_DIR LIBSSH2_LIBRARY )

mark_as_advanced( LIBSSH2_INCLUDE_DIR LIBSS2_LIBRARY )
